#!/usr/bin/env node
/**
 * Deterministic DS-2026 compiler.
 * Canonical sources: primitives.json, semantic.json, domain.json, typography.json, spacing.json.
 * Generated compatibility artifacts: tokens.css and colors.json.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(__dirname,'..'), T=path.join(ROOT,'tokens');
const read=n=>JSON.parse(fs.readFileSync(path.join(T,n),'utf8'));
const primitives=read('primitives.json'), semantic=read('semantic.json'), domain=read('domain.json'), typography=read('typography.json'), spacing=read('spacing.json');
const cssRef=value=>{ const m=String(value).match(/^\{color\.(primitive|derived)\.([^}]+)\}$/); if(!m) throw new Error('Unsupported semantic reference: '+value); return 'var(--'+m[2]+')'; };
const semName=(g,k)=>g==='status'&&k.startsWith('warning')?'status-warn'+k.slice('warning'.length):g==='action'&&k==='focus-ring'?'focus-ring':g+'-'+k;
const weightNameByValue=Object.fromEntries(Object.entries(typography.weights).map(([k,v])=>[String(v),k]));
const leadingTokenForRole={'display-01':'solid','display-02':'tight','heading-01':'tight','heading-02':'tight','heading-03':'snug','species':'tight','latin':'snug','body':'normal','small':'normal','data':'data','label':'tight','micro':'tight','lot-code-print':'tight'};
const familyVar={editorial:'--font-editorial',sans:'--font-sans',mono:'--font-mono'};
function generateCss(){
 const L=['/*',' * GENERATED FILE — DO NOT EDIT DIRECTLY',' * Sources: primitives.json · semantic.json · domain.json · typography.json · spacing.json',' * Generated by: scripts/build-tokens.mjs',' * System: Setas de la Peña · DS-2026 · Criterio Edition',' */','@import "fonts.css";','',':root {','  /* 1 · PRIMITIVE MINERAL PIGMENTS & GROUNDS */'];
 for(const [k,s] of Object.entries(primitives.color.primitive)) L.push('  --'+k+': '+s.value+';');
 L.push('','  /* Derived colour washes */');
 for(const [k,s] of Object.entries(primitives.color.derived||{})) L.push('  --'+k+': '+s.value+';');
 L.push('','  /* Legacy primitive aliases — compatibility only */','  --paper: var(--paper-100);','  --paper-panel: var(--paper-50);','  --paper-recessed: var(--paper-200);','  --ink: var(--ink-900);','  --ink-muted: var(--ink-500);','  --rule: var(--rule-500);','  --soil: var(--bark-700);','  --moss: var(--moss-700);','  --rust: var(--coral-700);','  --rust-tint: var(--coral-tint);','  --soil-tint: var(--bark-tint);','');
 L.push('  /* 2 · SEMANTIC ROLES */');
 for(const [g,items] of Object.entries(semantic.semantic)) for(const [k,s] of Object.entries(items)) L.push('  --'+semName(g,k)+': '+cssRef(s.value)+';');
 L.push('','  /* 3 · TYPE SCALE & ROLES */');
 for(const [k,v] of Object.entries(typography.weights)) L.push('  --weight-'+k+': '+v+';');
 L.push('');
 for(const [k,v] of Object.entries(typography.scale)) L.push('  --size-'+k+': '+v.size+';');
 L.push('  --size-micro: var(--size-micro-screen);','');
 L.push('  --leading-solid: '+typography.scale['display-01'].leading+';','  --leading-tight: '+typography.scale['display-02'].leading+';','  --leading-snug: '+typography.scale['heading-03'].leading+';','  --leading-normal: '+typography.scale.body.leading+';','  --leading-data: '+typography.scale.data.leading+';','');
 L.push('  --tracking-display: '+typography.scale['display-01'].tracking+';','  --tracking-tight: '+typography.scale['heading-01'].tracking+';','  --tracking-normal: '+typography.scale.body.tracking+';','  --tracking-label: '+typography.scale.label.tracking+';','  --tracking-micro: '+typography.scale.micro.tracking+';','');
 for(const role of ['display-01','display-02','heading-01','heading-02','heading-03','species','latin','body','small','data','label','micro','lot-code-print']){ const v=typography.scale[role]; if(!v) continue; const wn=weightNameByValue[String(v.weight)]||'regular', style=v.style?v.style+' ':'', leading=leadingTokenForRole[role]?'var(--leading-'+leadingTokenForRole[role]+')':String(v.leading); L.push('  --t-'+role+': '+style+'var(--weight-'+wn+') var(--size-'+role+')/'+leading+' var('+familyVar[v.family]+');'); }
 L.push('','  /* 4 · SPACING & GRID */');
 for(const [k,v] of Object.entries(spacing.scale)) L.push('  --space-'+k+': '+v+';');
 L.push('  --grid-columns: '+spacing.grid.columns+';');
 for(const [mode,v] of Object.entries(spacing.grid.modes)){ L.push('  --gutter-'+mode+': '+v.gutter+';'); L.push('  --margin-'+mode+': '+v.pageMargin+';'); }
 L.push('  --gutter: var(--gutter-field);','  --page-margin: var(--margin-field);','  --measure-prose: '+spacing.grid.measureProse+';','','  /* 5 · STRUCTURE & OPERATIONAL CONSTRAINTS */','  --radius-none: '+spacing.structure.radius.none+';','  --radius-sm: '+spacing.structure.radius.sm+';','  --rule-hairline: '+spacing.structure.rule.hairline+' solid var(--border-hairline);','  --rule-heavy: '+spacing.structure.rule.heavy+' solid var(--border-heavy);','  --rule-frame: '+spacing.structure.rule.frame+' solid var(--border-hairline);','  --shadow-none: none;','  --tap-target-min: '+spacing.structure.tapTargetMin+';','  --field-cell-min-height: '+spacing.structure.fieldCellMinHeight+';','  --print-code-x-height: '+spacing.structure.printCodeXHeight+';','  --pictogram-grid: '+spacing.structure.pictogram.grid+';','  --pictogram-stroke: '+spacing.structure.pictogram.stroke+';','','  /* 6 · DOMAIN CONTRACT SYMBOLS (labels stay in application i18n) */');
 for(const [k,v] of Object.entries(domain.domain.provenance)) L.push('  --provenance-'+k+'-symbol: "'+v.symbol+'";');
 for(const [k,v] of Object.entries(domain.domain.sync)) L.push('  --sync-'+k+'-symbol: "'+v.symbol+'";');
 if(domain.domain.status?.quarantine?.treatment) L.push('  --status-quarantine-border-style: '+domain.domain.status.quarantine.treatment+';');
 L.push('}','','/* Density profiles are semantic surface modes, never viewport aliases. */');
 for(const [mode] of Object.entries(spacing.grid.modes)) L.push('[data-mode="'+mode+'"] { --gutter: var(--gutter-'+mode+'); --page-margin: var(--margin-'+mode+'); }');
 L.push('[data-mode="culinary-market"] { --gutter: var(--gutter-culinary); --page-margin: var(--margin-culinary); }','[data-mode="archive"] { --accent-warm: var(--brand-accent); }','','@media print {','  :root { --size-micro: var(--size-micro-print); }','}');
 return L.join('\n')+'\n';
}
const camel=k=>k.replace(/-([a-z0-9])/g,(_,c)=>c.toUpperCase());
function generateColors(){
 const prim={}; for(const [k,v] of Object.entries(primitives.color.primitive)) prim[camel(k)]={...v};
 Object.assign(prim,{paper:{value:primitives.color.primitive['paper-100'].value,type:'color',role:'Legacy alias to paper-100'},ink:{value:primitives.color.primitive['ink-900'].value,type:'color',role:'Legacy alias to ink-900'},inkMuted:{value:primitives.color.primitive['ink-500'].value,type:'color',role:'Legacy alias to ink-500'},rule:{value:primitives.color.primitive['rule-500'].value,type:'color',role:'Legacy mineral rule'},soil:{value:primitives.color.primitive['bark-700'].value,type:'color',role:'Legacy alias to bark-700'},moss:{value:primitives.color.primitive['moss-700'].value,type:'color',role:'Legacy alias to moss-700'},rust:{value:primitives.color.primitive['coral-700'].value,type:'color',role:'Legacy alias to coral-700'}});
 const der={}; for(const [k,v] of Object.entries(primitives.color.derived||{})) der[camel(k)]={...v}; der.warningText={value:primitives.color.primitive['warning-text'].value,type:'color',role:'AA caution text'}; der.coralText={value:primitives.color.primitive['coral-700'].value,type:'color',role:'AA terracotta text'};
 const sem={}; for(const [g,items] of Object.entries(semantic.semantic)) for(const [k,v] of Object.entries(items)) sem[camel(g+'-'+k)]={value:v.value};
 return JSON.stringify({$schema:'https://design-tokens.org/schema.json',system:'Setas de la Peña · DS-2026',edition:'Criterio Edition',description:'GENERATED compatibility color view. Edit primitives.json and semantic.json, then run build-tokens.mjs.',color:{primitive:prim,derived:der,semantic:sem}},null,2)+'\n';
}
const outputs=new Map([['tokens.css',generateCss()],['colors.json',generateColors()]]);
const check=process.argv.includes('--check');
let drift=0;
for(const [name,content] of outputs){ const p=path.join(T,name); if(check){ const current=fs.existsSync(p)?fs.readFileSync(p,'utf8'):''; if(current!==content){ console.error('DRIFT '+name+' — run node scripts/build-tokens.mjs'); drift++; } } else { fs.writeFileSync(p,content,'utf8'); console.log('generated '+path.relative(ROOT,p)+' ('+content.length+' bytes)'); } }
if(check&&drift){ process.exit(1); }
if(check) console.log('token artifacts clean (0 drift)');
