'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const m=require('./operational-metrics'),p=require('./prototype-readiness'),q=require('./sync-queue'),nav=require('./navigation-state');
const lot=(id='L')=>({id,codigo:id,peseSeco:1,estado:'completado',recipeRef:{sKey:'p_ostreatus_gris',recipe:[{id:'paja',p:100}]}});
const harvest=(id='H',loteId='L',pesoFresco=500)=>({id,loteId,pesoFresco});
const storage=()=>{const data={};return {getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k]};};
test('empty records have no inferred final EB, hours or demo harvests',()=>{const d=m.derive();assert.equal(d.meanEB,null);assert.equal(d.freshKg,0);assert.equal(d.events.length,0);});
test('grams and kilograms preserve canonical final EB and deduplicate exact copies',()=>{const d=m.derive([lot(),lot()],[],[harvest(),harvest(),{id:'H2',loteId:'L',pesoFresco:0.5,unit:'kg'}]);assert.equal(d.meanEB,100);assert.equal(d.freshKg,1);assert.equal(d.harvests.length,2);});
test('partial outcomes are displayed but excluded from mean',()=>{const d=m.derive([{...lot(),estado:'fructificacion'}],[],[harvest()]);assert.equal(d.rows[0].be,50);assert.equal(d.meanEB,null);});
test('mean gives equal weight to final lots rather than fresh mass',()=>{const d=m.derive([lot(),{...lot('L2'),peseSeco:2}],[],[harvest(),harvest('H2','L2',2000)]);assert.equal(d.meanEB,75);});
test('missing harvest is not a measured zero; explicitly verified closed zero is eligible',()=>{assert.equal(m.derive([lot()],[],[]).meanEB,null);assert.equal(m.derive([{...lot(),outcome:{status:'completed-zero-yield',verified:true}}],[],[]).meanEB,0);});
test('blank, zero and nonfinite dry weights are never used as denominators',()=>{for(const dry of ['',0,'5abc',Infinity,null])assert.equal(m.derive([{...lot(),peseSeco:dry}],[],[harvest()]).meanEB,null);});
test('invalid masses and contradictory identities exclude final result rather than inflate it',()=>{for(const value of ['5abc',-1,'',NaN])assert.equal(m.derive([lot()],[],[harvest('bad','L',value)]).meanEB,null);const d=m.derive([lot()],[],[harvest(),harvest('H','L',700)]);assert.equal(d.meanEB,null);assert.equal(d.freshKg,0);assert.equal(d.issues[0].reviewable,false);});
test('conflicting harvest parent identities exclude both lots',()=>{const d=m.derive([lot(),lot('L2')],[],[harvest(),harvest('H','L2'),harvest('H2','L2')]);assert.equal(d.meanEB,null);});
function fixture(){const s=storage();p.persist(s,[['sdp_bit_lotes',[lot()]],['sdp_bit_bolsas',[{id:'B1',loteId:'L',estado:'contaminada'},{id:'B2',loteId:'L',estado:'dudosa'}]],['sdp_bit_cosechas',[harvest()]]]);return {storage:s,prototype:p,queue:q,auth:{uid:'operator'},role:'produccion',anomalyId:'bolsa:B1:estado',decision:'validado',reason:'Observación comprobada',id:'review-1',at:'2026-10-07T12:00:00Z'};}
test('review survives reload with actor, date, reason and event-specific identity',()=>{const f=fixture();m.saveReview(f);const d=m.derive(p.read(f.storage,'sdp_bit_lotes'),p.read(f.storage,'sdp_bit_bolsas'),p.read(f.storage,'sdp_bit_cosechas'));assert.equal(d.issues.find(i=>i.id==='bolsa:B1:estado').review.operatorId,'operator');assert.equal(d.issues.find(i=>i.id==='bolsa:B2:estado').review,null);assert.equal(p.read(f.storage,'sdp_sync_queue')[0].args[1].lifecycleEvents[0].type,'metrics_review');});
test('unauthenticated and operator roles cannot review, reason required',()=>{const f=fixture();for(const bad of [{auth:null},{role:'operario'},{reason:' '}])assert.throws(()=>m.saveReview({...f,...bad}));assert.equal(p.read(f.storage,'sdp_sync_queue').length,0);});
test('changed source snapshot requires a fresh review; historical decisions remain',()=>{const f=fixture(),before=m.derive(p.read(f.storage,'sdp_bit_lotes'),p.read(f.storage,'sdp_bit_bolsas'),p.read(f.storage,'sdp_bit_cosechas')).issues[0];m.saveReview(f);p.persist(f.storage,[['sdp_bit_bolsas',[{id:'B1',loteId:'L',estado:'dudosa'}]]]);assert.throws(()=>m.saveReview({...f,id:'review-2',expectedSnapshot:before.snapshot}),/cambió/);const d=m.derive(p.read(f.storage,'sdp_bit_lotes'),p.read(f.storage,'sdp_bit_bolsas'),p.read(f.storage,'sdp_bit_cosechas'));assert.equal(d.issues[0].review,null);assert.equal(d.reviews.length,1);});
test('storage failure rolls back the review and queue together',()=>{const f=fixture(),original=f.storage.setItem;let writes=0;f.storage.setItem=(k,v)=>{if(++writes===3)throw Error('quota');original(k,v);};assert.throws(()=>m.saveReview(f),/quota/);assert.equal(p.read(f.storage,'sdp_bit_lotes')[0].lifecycleEvents,undefined);assert.equal(p.read(f.storage,'sdp_sync_queue').length,0);});
test('separate reviews preserve separate outbox events and merge across devices',()=>{const f=fixture();m.saveReview(f);m.saveReview({...f,id:'review-2',anomalyId:'bolsa:B2:estado',decision:'corregir'});assert.equal(p.read(f.storage,'sdp_sync_queue').length,2);assert.equal(p.read(f.storage,'sdp_bit_lotes')[0].lifecycleEvents.length,2);});
test('metrics route and subtab are normalized and preserve unrelated parameters',()=>{assert.deepEqual(nav.readLocation('?view=metricas&metricsTab=supervision'),{view:'metricas',metricsTab:'supervision'});assert.equal(nav.readLocation('?view=metricas&metricsTab=bogus').metricsTab,'rendimiento');const win={location:{href:'https://setas.local/?view=home&lot=X'},history:{pushState(a,b,u){win.location.href=u.href;}}};nav.navigate(win,'metricas',{metricsTab:'trabajo'});assert.match(win.location.href,/metricsTab=trabajo/);assert.match(win.location.href,/lot=X/);nav.navigate(win,'home');assert.doesNotMatch(win.location.href,/metricsTab=/);});

test('malformed and duplicate lifecycle events cannot crash or inflate all-view derivation',()=>{const event={id:'e',type:'observation'};const d=m.derive([{...lot(),lifecycleEvents:[null,event,event,{type:'unknown'}]}],[],[harvest()]);assert.equal(d.events.length,2);assert.equal(d.issues.filter(i=>i.id.startsWith('evento:')).length,2);});
test('review preserves event envelope and the next canonical action identity',()=>{const f=fixture(),sheet=require('./batch-sheet');m.saveReview(f);const log=p.read(f.storage,'sdp_bit_lotes')[0].lifecycleEvents;assert.equal(log[0].id,'review-1');assert.equal(sheet.verifyEventChain(log).valid,true);const next=sheet.appendBatchEvent(log,{batchId:'L',action:'observation',operatorId:'operator',payload:{nota:'Seguimiento'}});assert.equal(next.at(-1).seq,2);assert.equal(next.at(-1).id,'L-2');assert.equal(sheet.verifyEventChain(next).valid,true);});
test('closed missing or invalid EB is labelled as data missing rather than partial',()=>{for(const cosechas of [[],[harvest('H','L',5000)]]){const d=m.derive([lot()],[],cosechas);assert.equal(d.rows[0].exclusionReason,'missing-or-invalid-eb');assert.equal(d.issues.some(i=>i.id==='lote:L:datos'),true);}});
test('review refuses malformed lifecycle tail without writing a broken chain',()=>{const f=fixture();p.persist(f.storage,[['sdp_bit_lotes',[{...lot(),lifecycleEvents:[{id:'legacy',type:'observation'}]}]]]);assert.throws(()=>m.saveReview(f),/historial/);assert.equal(p.read(f.storage,'sdp_sync_queue').length,0);});
