#!/usr/bin/env python3
"""
generate_index.py — Genera INDEX.yaml a partir del contenido real de la KB.

Escanea todos los archivos .md en knowledge_base/, extrae frontmatter YAML,
y genera un catálogo máquina-legible completo.

Resuelve DEC-011: "INDEX.yaml es solo plantilla, script de generación pendiente."

Uso:
    python3 scripts/generate_index.py
    python3 scripts/generate_index.py --dry-run   # solo imprime, no escribe
"""

import os
import sys
import yaml
import re
from datetime import datetime
from pathlib import Path

KB_ROOT = Path(__file__).resolve().parent.parent / "knowledge_base"
INDEX_PATH = KB_ROOT / "INDEX.yaml"

# Directories to skip
SKIP_DIRS = {"archive_phase0", "source_pdfs", "archive", "templates", ".DS_Store"}
SKIP_FILES = {"INDEX.yaml", "README_MCP.md"}


def extract_frontmatter(filepath: Path) -> dict | None:
    """Extract YAML frontmatter from a markdown file."""
    try:
        content = filepath.read_text(encoding="utf-8")
    except Exception:
        return None

    match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if not match:
        return None

    try:
        return yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None


def get_relative_path(filepath: Path) -> str:
    """Get path relative to knowledge_base/."""
    return str(filepath.relative_to(KB_ROOT))


def scan_kb() -> list[dict]:
    """Scan knowledge_base/ and build document entries."""
    entries = []

    for root, dirs, files in os.walk(KB_ROOT):
        # Filter out skip dirs
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]

        root_path = Path(root)
        rel_dir = root_path.relative_to(KB_ROOT)

        for filename in sorted(files):
            if filename in SKIP_FILES:
                continue
            if not filename.endswith((".md", ".yaml")) or filename == "INDEX.yaml":
                continue

            filepath = root_path / filename
            rel_path = get_relative_path(filepath)

            entry = {
                "path": rel_path,
                "filename": filename,
                "directory": str(rel_dir) if str(rel_dir) != "." else "root",
                "size_bytes": filepath.stat().st_size,
            }

            # Extract frontmatter for .md files
            if filename.endswith(".md"):
                fm = extract_frontmatter(filepath)
                if fm:
                    if "title" in fm:
                        entry["title"] = fm["title"]
                    if "category" in fm:
                        entry["category"] = fm["category"]
                    if "load_priority" in fm:
                        entry["load_priority"] = fm["load_priority"]
                    if "last_reviewed" in fm:
                        entry["last_reviewed"] = str(fm["last_reviewed"])
                    if "confidence" in fm:
                        entry["confidence"] = fm["confidence"]
                    if "related_documents" in fm:
                        entry["related_documents"] = fm["related_documents"]
                else:
                    entry["title"] = filename.replace(".md", "").replace("_", " ").title()
                    entry["has_frontmatter"] = False
            elif filename.endswith(".yaml"):
                entry["title"] = filename.replace(".yaml", "").replace("_", " ").title()
                entry["type"] = "metadata"

            entries.append(entry)

    return entries


def build_index(entries: list[dict]) -> dict:
    """Build the full INDEX.yaml structure."""
    # Group by directory
    by_dir = {}
    for entry in entries:
        d = entry["directory"]
        if d not in by_dir:
            by_dir[d] = []
        by_dir[d].append(entry)

    return {
        "schema_version": "2.0",
        "generated_at": datetime.now().isoformat(),
        "generator": "scripts/generate_index.py",
        "total_documents": len(entries),
        "directories": len(by_dir),
        "catalog": by_dir,
    }


def main():
    dry_run = "--dry-run" in sys.argv

    print(f"Scanning {KB_ROOT} ...")
    entries = scan_kb()
    print(f"Found {len(entries)} documents")

    index = build_index(entries)

    output = yaml.dump(index, default_flow_style=False, allow_unicode=True, sort_keys=False, width=120)

    if dry_run:
        print("\n--- DRY RUN (no files written) ---\n")
        print(output)
    else:
        # Preserve the original schema comments at the top
        header = (
            "# INDEX.yaml — Machine-Readable Document Catalog\n"
            "# Setas de la Peña Knowledge Base\n"
            "# Auto-generated by scripts/generate_index.py\n"
            f"# Last generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
            "# DO NOT EDIT MANUALLY — re-run the script to update.\n"
            "#\n"
            "# This file resolves DEC-011: full INDEX.yaml population.\n"
            "# See 00_project/INDEX_GENERATION_SPEC.md for schema details.\n\n"
        )
        INDEX_PATH.write_text(header + output, encoding="utf-8")
        print(f"Written to {INDEX_PATH}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
